### ISSUE TITLE
paroutes testing

### ISSUE THREAD

**Issue by JunSeok94** [batistagroup/DirectMultiStep#4]
Hi, I'm from South Korea and appreciate your interesting paper.

After running your code, I cannot get paroutes metric using paroutes package with some kinds of error. Is ther any paroutes inference code?

Thanks a lot for you amazing insight :)

**Comment by randyshee** [comment]
Hi Junseok,

Thank you for your interest.

The format of the routes from PaRoutes (see the example in [PaRoutes/analysis/README.md](https://github.com/MolecularAI/PaRoutes/blob/main/analysis/README.md)) differs from our format:
```
class FilteredDict(TypedDict, total=False):
    smiles: str
    children: List["FilteredDict"]
```
We filter their routes by removing keys other than "smiles" and "children", and we only keep nodes where the "type" is "mol" (refer to ```filter_mol_nodes``` in [PreProcess.py](https://github.com/batistagroup/DirectMultiStep/blob/main/DirectMultiStep/Utils/PreProcess.py) for specifics). You can transform our format back to theirs, but note that information such as the atom-mapped reaction SMILES for the reaction nodes will not be included.

I'm closing this issue, but feel free to comment here if you need further clarification!
